---

- name: Deploy Application
  hosts: webservers
  roles:
    - common
    - { role: rubystatic, when: "user == 'vagrant'" }
    - deployment
    - nginx_postinstall
    - supervisor_postinstall
  tags:
    - webserver
    - wait
    - deployment

- name: Common PostInstall
  hosts: webservers
  roles:
    - common_postinstall
  tags:
    - webserver
    - wait
    - deployment
