---

- name: setup haproxy configuration
  sudo: yes
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items: haproxy_templates
  tags:
    - reload_haproxy
  notify:
    - reload haproxy
