---

- name: Collect static files
  sudo_user: "{{ user }}"
  raw: "source {{ virtualenv_file_activate }} &&
        source {{ virtualenv_file_postactivate }} &&
        cd {{ app_dir }} &&
       python manage.py collectstatic --noinput"
  when: "user == 'vagrant'"
  tags:
    - static
    - collect
    - apps
  register: collect_static_files
