---

- name: Install haproxy
  when: ansible_os_family == 'Debian'
  sudo: yes
  apt:
    name: "{{ haproxy_name_package }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - haproxy
