---
name_inventory: production
path_inventory: provision/ansible/inventories/sandbox/production
vagrant:
  limit: ''
  verbose: 'vvvv'
  sudo: true

servers:
  - name: 1.nodejs-tweets.hadenlabs.com
    ip: 192.168.33.50
    box: ubuntu-14.4
    url: https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.04/ubuntu-14.04-amd64.box
    hostname: 1.nodejs-tweets.hadenlabs.com
    ram: 512
