---

common_package_dependencies:
  - "curl"
  - "zip"
  - "rsync"
  - "wget"
  - "openssl"
  - "libssl-dev"
  - "libpq-dev"
  - "bzip2"

common_dependencies:
  - name: "python2.7-dev"
    version: ""
  - name: "python-dev"
    version: ""
  - name: "python-pip"
  - name: "libpq-dev"
  - name: "git"
  - name: "python-setuptools"
  - name: "python-software-properties"

# PostgreSQL
postgresql_version: 9.4
postgresql_listen_addresses:
  - '*'
postgresql_databases:
  - name: '{{ postgresql_database_name }}'
    port: '{{ postgresql_port }}'

postgresql_users:
  - db: '{{ postgresql_database_name }}'
    name: '{{ postgresql_user }}'
    password: '{{ postgresql_pass }}'
    priv: ALL
    role_attr_flags: SUPERUSER
